# This is intended for local testing of your production environment only
# Unable to connect to postgres container atm


version: '2'

services:
  db:   
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin123
    restart: always
    image: postgres
    ports:
      - "5432:8001"
    expose:
      - "5432"

  app:
    depends_on:
      - "db"
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
    ports:
      - "8000:8000"
