# INTENDED FOR LOCAL TESTING OF PRODUCTION ENVIRONMENT ONLY

version: '2'

services:
  postgres:   
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin123
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"

  app:
    depends_on:
      - postgres
    build:
      context: ""
      dockerfile: ./Dockerfile
    links:
      - postgres
    ports:
      - "8000:8000"
    expose:
      - "8000"
