version: '2'

services:
  postgres:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin123
    restart: always
    image: postgres
    expose:
      - "5432"
  app:
    environment:
      DATABASE_URL: postgres://postgres:Admin123@postgres/postgres
    build:
      context: .
      dockerfile: ./.docker-compose/Dockerfile
    links:
      - postgres:postgres
    ports:
      - "8000:8000"
    expose:
      - "8000"
